// Code generated by ent, DO NOT EDIT.

package ent

import "github.com/coksnuss/entgql-noders-bug/ent/schema/types"

// CreatePostInput represents a mutation input for creating posts.
type CreatePostInput struct {
	Title     string
	CreatorID *types.UserID
}

// Mutate applies the CreatePostInput on the PostMutation builder.
func (i *CreatePostInput) Mutate(m *PostMutation) {
	m.SetTitle(i.Title)
	if v := i.CreatorID; v != nil {
		m.SetCreatorID(*v)
	}
}

// SetInput applies the change-set in the CreatePostInput on the PostCreate builder.
func (c *PostCreate) SetInput(i CreatePostInput) *PostCreate {
	i.Mutate(c.Mutation())
	return c
}
